version: "3.9"

services:
  mariadb:
    image: mariadb
    container_name: my_mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: my_app
    env_file:
      - .env
    ports:
      - "3000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    depends_on:
      - mariadb
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:4000/healthcheck"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

    app_prod:
      image: mon_utilisateur/graphql-auth:0.2
      container_name: my_app_prod
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=production
      depends_on:
        - mariadb
